version: '3'

services: 
  postgres:
    image: postgres
    restart: always
    container_name: postgres_db
    env_file:
      - flow.env
    ports:
      - '5432:5432'
  minio:
    image: docker.io/bitnami/minio:2021
    restart: always
    container_name: minio
    ports:
      - '9500:9000'
      - '9501:9001'
    env_file:
      - flow.env
    volumes:
      - ./S3_VOLUME:/data
  minio-mc:
    container_name: minio-mc
    image: minio/mc:latest
    restart: always
    env_file:
      - flow.env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/mlflow;
      sleep infinity;
      exit 0;
      "
  mlflow:
    build: docker_files/
    restart: always
    container_name: mlflow
    env_file:
      - flow.env
    ports:
      - '5500:5000'
    command: bash ../run_mlflow.sh
    volumes:
      - ./data_trainer_app:/usr/src/app/data_trainer_app
